### ISSUE TITLE
Forge recognizes the mod but it doesn't do anything

### ISSUE THREAD

**Issue by tuca1234567890** [Laike-Endaril/Login-HP-Fix#2]
I know this project is discontinued, but never hurts to try, right?
As the title says, the mod is recognized by Forge and loaded, but when I log into my singleplayer world it doesn't do anything. 
I don't know what else to add, since there's nothing in the logs pointing to the error.
Let me know if I should attach something like logs or screenshots.

**Comment by Laike-Endaril** [comment]
I know this was from a long time ago, so if you're not interested at this point, feel free to ignore the rest of this post!

Also posting this in case anyone else comes along.

First, just to be clear, if your modpack is already working as it should, then this mod SHOULDN'T DO ANYTHING AT ALL!  This mod attempts to fix issues where players otherwise log in with a different amount of health than they had when they logged out.  It's not guaranteed to work, but it sure did in the modpack I was helping with when I made it.

If someone sees this and has that specific issue (health having a different value when logging in than it was when logging out) even with this mod installed, I would need to know where the cause is coming from at a bare minimum in order to look into it (ie. what other mod(s) and/or circumstances are causing the issue in the first place).

If you (or anyone else) is still interested in this, leave a comment and I can look into it, (assuming I have enough information to go off of!)
